/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_launcher_MainActivity */

#ifndef _Included_com_example_launcher_MainActivity
#define _Included_com_example_launcher_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_launcher_MainActivity
 * Method:    initHooks
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_launcher_MainActivity_initHooks
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_launcher_MainActivity
 * Method:    getStringUTF
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_launcher_MainActivity_getStringUTF
  (JNIEnv *, jobject);

/*
 * Class:     com_example_launcher_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_launcher_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_launcher_MainActivity
 * Method:    release
 * Signature: ()
 */
JNIEXPORT void JNICALL Java_com_example_launcher_MainActivity_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
